# ./gunicorn-gevent-patched.yml
version: "3.7"
services:
  flask_app_gunicorn_patched:
    init: true
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    command: ["gunicorn","--workers","1","--timeout","30","--keep-alive","2","--bind","0.0.0.0:3000","--worker-class","gevent","patched:app"]
    environment:
      - PORT_API=4000
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - slow_api

  slow_api:
    init: true
    build: ./slow_api
    environment:
      - PORT=4000
    expose:
      - "4000"