# ./gunicorn-gevent-only.yml
version: "3.7"
services:
  flask_app_gunicorn:
    init: true
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    command: ["gunicorn","--workers","1","--timeout","30","--keep-alive","2","--bind","0.0.0.0:3000","--worker-class","gevent","sql_app:app"]
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mongo

  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root